### PR TITLE
Custom coloring

### LINKED ISSUE #9: Config file for themes and overriding coloring for some subcommands
# Expected Behavior

Configure coloring via config file, such as `~/.kube/kubecolor.yml` or `~/.config/kubecolor.yml`

Want to from config be able to enable/disable coloring for subcommands, as well as enable some coloring logic like the one used on `kubectl get` but on a krew plugin's subcommands.

Would also be nice to config the theme used.

# Current Behavior

Only very little configurable via env vars and flags

## Context

I can help implementing this, if you'd accept this kind of feature

### PR DESCRIPTION
**Pull request by applejag**
# Description

Based on @prune998's work in #33 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## What you changed

- Removed previous color code in `./color` package
- Added configs via Viper
  - Looking at env vars starting with `KUBECOLOR_`
  - Looking at YAML file at path from env var `KUBECOLOR_CONFIG`
  - Looking at YAML file at `~/.kube/color.yaml`
- Rewrote flag parsing to allow `--force-colors=false` syntax and to integrate with Viper
- Added `Config` struct at `./config/config.go`, with `Theme` struct defined in `./config/theme.go`
  - With "per-use case" color settings, such as `KUBECOLOR_THEME_APPLY_CREATED`, to allow fine-grained control
  - With a "fallback/default" mechanic, implemented with some basic reflection
- Updated all useses of old `./color` package with new `Theme` struct
- Replaced all `\033` escape characters in tests with `\e` to make it more readable, and to stop my editor from complaining about those files
- Fixed some bugs in `kubectl describe` table header parsing
- Added flag parsing found in `kubectl options` to `./scanner/describe` package

## Why you think we should change it

There's some things I want to explain.

### Design of theming

I want kubecolor to allow fine-grained control over its coloring. Just overriding a small handfull of what kubecolor defines as "red" does not fly with me. It feels too limiting. But there are some issues with that approach:

1. Too many configs for the average user to just modify some few colors
2. When kubecolor adds more features (for example log parsing) then the coloring of that would not match their theme

To counter these two issues, I went with a "fallback/defaults" system. We have a set of base colors, with names inspired by UI coloring frameworks like [Bootstrap](https://getbootstrap.com/docs/4.1/utilities/colors/#color) (e.g "primary", "secondary", "danger"). The other color options default to one of these base colors. This way, a simple user only needs to update the base colors (e.g `KUBECOLOR_THEME_BASE_DANGER`), and then they're set. But they could also delve deeper and update colors on a more specific degree (e.g `KUBECOLOR_THEME_STATUS_ERROR`)

### Reflection and Go parsing

There are some parts of this PR that might feel scary, such as the reflection part in `./config/theme.go`, or the Go-parsing part in `./internal/cmd/configdoc`. They were just a means to an end that I was already familiar with. For the reflection, you could look at commit <https://github.com/kubecolor/kubecolor/pull/59/commits/498f58db4f04ba1a4b3f8145724c6f18907eb113> for a before and after, as I first tried to solve it without reflection. But that was quite error prone and a lot of boilerplate.

One of my challenges in `./config/theme.go` was mixing between using structs (e.g what's found in `config.NewBaseTheme()`) and using Viper keys (e.g `viper.Set("theme.status.error", ...)`). One could get away with only using structs by for example marshalling the Viper config into YAML and then reading it back in, but that's quite inefficient. There's also an issue with the order of loading the config, because I want a user to be able to set `KUBECOLOR_THEME_BASE_DANGER` and then have the default-logic use the user's value when it applies the default on `KUBECOLOR_THEME_STATUS_ERROR`.

### Color parsing

I initially said that we could make use of [`github.com/gookit/color.ParseCodeFromAttr`](https://pkg.go.dev/github.com/gookit/color#ParseCodeFromAttr), but after a short while I realized that their parsing had some flaws that I did not want to adopt into kubecolor. The parsing is quite simple, so I ended up rewriting most of it into kubecolor's `./config/color.go` file. 

One of my biggest gripes is that the syntax was not really self-explanatory about when to use semicolon `;` or when to use comma `,`. E.g `"fg=white;op=bold,underscore"`. Also, forcing the user to write `fg=` when they only want to change the text color felt excessive.

Compared to gookit's parser, kubecolor's parser:

- Use colon `:` for separator instead of semicolon `;`, to mimic LSCOLORS.
- Treats `"red"` as an implicit `"fg=red"`.
- No prefix for modifiers, meaning it's `"bold"` instead of `"op=bold"`.
- Adds automatic color downgrade based on terminal support. The gookit library has all these `color.SupportTrueColor()` functions, but they were not used in the `color.ParseCodeFromAttr()` stack.
- Modifiers also are not a list separated by comma `,`. Instead you just supply more modifiers with the colon `:` separator.
- Uses different color names. So no mixed casing like `"lightRed"` but instead all lower as `"lightred"`. Also allows optional dash as separator for clarity: `"light-red"`.
- Skips HSL parsing, as the syntax was quite non-standard of `hsl(0-1, 0-1, 0-1)`, whereas in CSS it's `hsl(0-360, 0%-100%, 0%-100%)`.
- 256-bit color syntax has higher parsing prio than 3-character hex. So strings like `255` are parsed as 256-bit color code instead of `#225555`

As a result, instead of `"fg=white;op=bold,underscore"`, we have `"white:bold:underscore"`. Much nicer.

## Related issue (if exists)

Closes #9

### CODE REVIEW

**Comment by prune998** [comment]
LGTM. Just ping me when you're done and want a review. Seems pretty close to what I did but using env vars instead of a config key: val... I'm good with both, so let's move forward with yours... 

I guess we don't need a `config.file` if we can set the colors in the envs... WDYT ?

**Comment by applejag** [comment]
> LGTM. Just ping me when you're done and want a review. Seems pretty close to what I did but using env vars instead of a config key: val... I'm good with both, so let's move forward with yours...
> 
> I guess we don't need a `config.file` if we can set the colors in the envs... WDYT ?

I think one does not exclude the other. We could start with env vars and then also add a config file later.

Having a yaml config file with a JSON schema could be super nice, but then still allowing setting theme via env vars for better integration.

My current solution is dangerously close to just ripping it out and using viper instead for config.

**Comment by prune998** [comment]
anything I can do to help ?

**Comment by applejag** [comment]
@prune998 yea, at this point I'm soon open for review. The PR grew a lot on me, so sorry about that.

I've not yet updated the PR description of all changes, but you're free to add comments already

**Pull request merged**
